### ISSUE TITLE
Stream response is either empty or not retrievable

### ISSUE THREAD

**Issue by tripleten** [felixdorn/twitter-stream-api#20] opened 2022-12-25 16:39 UTC
This does not echo the tweet containing the hashtag I created the rule for-

```
$stream->listen($connection, function (object $tweet) {
	echo $tweet->data->text . PHP_EOL;
});
```

**Comment by Barfooss** [comment] 2022-12-28 14:38
I have the same problem. I verified with curl, that the filter is correct, and also tried out another library which depends on the 0.20 tags of this library (spatie/twitter-streaming-api), which seems to work, but has far lesser features.

I also noticed, that Postman is unable to get data as well because it waits for the completion of the response body. I suspect something similar is going on here, but i have no idea. I saw that Guzzle is being used, maybe an upstream change is responsible for that?

**Comment by Barfooss** [comment] 2022-12-29 00:12
I found the Solution. It has nothing to do with this library, it's located in the used `Parser` class from [salsify/json-streaming-parser](https://github.com/salsify/jsonstreamingparser). The `bufferSize` is set for `stream_get_line`, but not on the underlying Guzzle http-body response stream.

Setting `stream_set_chunk_size($this->stream, $this->bufferSize);` in the `parse()` function of `Parser` class solves the Problem. Tweets are coming in instantly if set to a low value of for example 40 (needs at least 2 Twitter posts before they come in).

**Comment by Barfooss** [comment] 2022-12-29 00:41
I have made a pull request in the json-streaming-parser repo. [pull request](https://github.com/salsify/jsonstreamingparser/pull/95)

**Comment by tripleten** [comment] 2022-12-29 13:42
> I have the same problem. I verified with curl, that the filter is correct, and also tried out another library which depends on the 0.20 tags of this library (spatie/twitter-streaming-api), which seems to work, but has far lesser features.
> 
> I also noticed, that Postman is unable to get data as well because it waits for the completion of the response body. I suspect something similar is going on here, but i have no idea. I saw that Guzzle is being used, maybe an upstream change is responsible for that?
> 
> Edit: I tested the versions down to 1.0.0 with filter bio_location:nyc (for higher tweet amounts - because of buffer size), and none of them work :(
> 
> Edit Edit: forget what i have said, at least 2.2.0 seems to work, if there are many tweets, you just need to let the amount go very high, i have bufferSize set to 1. don't know if that has something to do with it

Does 2.2.0 really work without you making any changes to the underlying parser library?

**Comment by tripleten** [comment] 2022-12-29 13:45
> I found the Solution. It has nothing to do with this library, it's located in the used `Parser` class from [salsify/json-streaming-parser](https://github.com/salsify/jsonstreamingparser). The `bufferSize` is set for `stream_get_line`, but not on the underlying Guzzle http-body response stream.
> 
> Setting `stream_set_chunk_size($this->stream, $this->bufferSize);` in the `parse()` function of `Parser` class solves the Problem. Tweets are coming in instantly if set to a low value of for example 40 (needs at least 2 Twitter posts before they come in).

@felixdorn mentioned in one of the closed issues about the stream buffer size, have a look at it [here](https://github.com/felixdorn/twitter-stream-api/issues/15#issuecomment-1227148243).

**Comment by Barfooss** [comment] 2022-12-29 18:24
Yes i saw that, thank you. the Issue is, that the underlying Guzzle HTTP-Client is also buffering the response stream. So the buffer-size can only be seen as "on top" if its over 8192kB (or whatever it is). 

As long as the Twitter response stream is below the buffer size of Guzzle  **itself**, data is not beeing pushed to the `stream_get_line`.

At least that is what i observed and interpreted. See the pull request i made for the other library and see for yourself :).

and yes, 2.2.0 did work, if i had chosen a filter with a large amount of tweets, like `bio_location:nyc`. It takes roughly 15 seconds till tweets are streaming in.

**Comment by felixdorn** [comment] 2022-12-29 22:17
I'm not sure which version you're using, but the buffer size issue has been fixed in the last release.

**Comment by uintaam** [comment] 2023-03-15 07:42
I'm having the same issue just installed this library today. With a low volume of tweets I get no results unless I add `stream_set_chunk_size($this->stream, $this->bufferSize);` in salsify/json-streaming-parser's Parser::parse function

felixdorn/twitter-stream-api - v2.2.0
salsify/json-streaming-parser - v8.2.0

**Comment by felixdorn** [comment] 2023-03-18 16:36
There's not much I can do unless a new release is issued upstream and I have too little available time to fork it and publish a clone on Packagist (considering that means I'll have to maintain the package).

**Comment by felixdorn** [comment] 2023-04-20 14:05
I copied over the relevant files from the two packages and with some tweaks, it finally works. If you try it, let me know how it went.

**Closed** 2023-04-20 14:04 UTC
